name: lint
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linter
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: yarn install
    - name: Add prettier ignore
      run: echo -e '*\n!.ts' > .prettierignore
    - name: Lint
      uses: wearerequired/lint-action@v2.3.0
      with:
        prettier: true